### ISSUE TITLE
Exception: Second auth step failed.

### ISSUE THREAD

**Issue by ThomasGugler** [marazt/garmin-connect-client#1]
hi,

 client.Authenticate().Wait();
seems not to work, i get this error:

Exception: Second auth step failed.

**Comment by marazt** [comment]
Hi @ThomasGugler,

I've found such problem a few weeks ago before I left for vacation. There is some change in Garmin Connect login process (probably new redirect/session issue). I need to solve this too cause some of my services stopped working :(, so I hope I'll fix is ASAP.

Regards,

Marek

**Comment by ThomasGugler** [comment]
hi 
are there any news from your side?
i tried to debug but was not able to fix the bug :/
